apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: digitops-service
  template:
    metadata:
      labels:
        app: digitops-service
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c", "apt-get update && apt-get install -y netcat && while true; do echo -e 'HTTP/1.1 500 Internal Server Error\\n\\n' | nc -l -p 80; done"]   
