name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        # Delete existing pods to force update
        kubectl delete pods -l app=digitops-service -n digitops --ignore-not-found
        
        # Update the deployment with new image
        helm upgrade --install digitops-service ./digitops-app \
          --namespace digitops \
          --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          --set image.tag=${{ github.sha }} \
          --set image.pullPolicy=Always \
          --create-namespace

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/digitops-service-deployment -n digitops --timeout=180s
        echo "Current pods:"
        kubectl get pods -n digitops
